apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: number4
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: amazon_key_new  # Имя публичного ключа, загруженного в AWS

  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: amazon_key_new  # Имя публичного ключа, загруженного в AWS
