apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: my-website
        image: 01yura/my-website:3.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 80