apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: my_app
        image: 01yura/k8s-web-to-nginx-ru:3.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 3000