apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
spec:
  type: NodePort
  selector:
    app: k8s-web-to-nginx
  ports:
    - protocol: TCP
      port: 3000   # внутренний порт пода, на котором работает приложение контейнера
      targetPort: 3000   # порт, на который будет направлен трафик внутри пода
      nodePort: 32333   # внешний порт воркер ноды, доступны из интернета. С него трафик пойдет на targetPort