apiVersion: v1
kind: Service
metadata:
  name: my_app
spec:
  type: NodePort
  selector:
    app: my_app
  ports:
  - port: 3000   # внутренний порт пода, на котором работает приложение контейнера
    targetPort: 3001   # порт, на который будет направлен трафик внутри пода
    NodePort: 3333   # внешний порт воркер ноды, доступны из интернета. С него трафик пойдет на targetPort