apiVersion: v1
kind: Service
metadata:
  name: my-website
spec:
  type: NodePort
  selector:
    app: my-website
  ports:
    - protocol: TCP
      port: 80   # внутренний порт пода, на котором работает приложение контейнера
      targetPort: 80   # порт, на который будет направлен трафик внутри пода
      nodePort: 32333   # внешний порт воркер ноды, доступны из интернета. С него трафик пойдет на targetPort